language: ruby
jdk:
- oraclejdk8
rvm:
- 2.3.1
before_install:
- openssl aes-256-cbc -K $encrypted_4d31dfc96dea_key -iv $encrypted_4d31dfc96dea_iv
  -in etc/secrets -out ../secrets.tar -d
- "(cd ../ && tar xvf secrets.tar)"
- chmod 600 ../release.asc
- gpg --import ../release.asc
install:
- rvm use 2.3.1
- gem install bundler
- bundle install
script: buildr clean package mcrt:publish_if_tagged
git:
  depth: false
env:
  global:
  - secure: pmL6s477y3pGvA8sNFBTy6RzIXaw2SOT3mfRGbFWLJKy4riOhvBZwji513ezx+CZKGyfKdTgeGnk0GuhiB/MmH7WnsNeUgSdneCVjIYXNTxLM//pz+neIcq8kaoGbRTgmpJJsLuZTxjbu63VWPfHXk8ZaDF9usLMBULl/dJ2vRWd0hsl/Ym18cBsA8GnYiiAgeSPku3iFR32GBnsT3lPK1SIAR3AYh742oYT1kwT1DnpRCFsCd66krIPd6cqngBS2XRfpAdp+Qx3PCmziNfFu2j9VKEOM0Xm36YJ6afjxdSknnzMaRQwwG4OQCzefstPFmhSrr8UmFjiI0m71r4EuaDbvxifV+rOGQLQRExz7iIEnRCqe751bTG3SbtzMof50ZnHKdq9XtlyMJPaNHwwCG2PH2Laf93HkO0uTpiUwGC3mR0eMaGtPlUqXnCLUiH/KBFWDksWbIdiKG1VOm2zO2b/v0fgcszzIxzGwMgGndP8BBc3MVmBlRgohKgBoTbDZmeot3utrab0YJO3cNuj742B8HhU8SBaMAGmyrSfio4SJ4UkMtN1Jhd/9bMOnVYsBz3+T4Iq00a4+uw6TqT5p01miuNI4h0q4GhvMTG4IOo7t7lgxt2PZdpL1QkJLjhSP4Phxpt5qwvLWVK8ovxtVE7CXnQtWU48Vb9XMdbkdmE=
  - secure: ZgZzKzkpO8nD17I9kRzA0qFqtVueIyyzHo/vJSx5tHDEprBqcHzhyQHcXa0io7yJG4EGfP8Uov3+8ilDbWACwFxD3+PBORVvbwy4+61lcdYP6InAnXEldQH9A5k5nmwORzwhs4+5vGcwAvv0FfF/ZuAov82k3eG7UAFPqVv2Q/B6lWtSPmBheEqJQ3GoXUiI18poxMB8T9aHmw7KrzsKmOfnJAbDbqsul1J8EqfBzMUbVEd3Zn1W1tSAAHh56tr+1cMRNSqFnrfjOm5hC2BtPEuxvx+JAmgdYfVQ5VPEdeA9IAFI46pQX9geSE/fwSjgq6BVRJ0n2WD08u1KgHr5VQbXGI+NNvPK8toGZegkmAnRdsZJsJHoRIsKWOkWPzdZguhmLsMCr+CegGOnVGUUHMinmviykoBV66yf0K21hnbmoOX/+modprzitVef74wFO9+859jRiz1TBvNNo6H5KRmumif3MB53jDdpq08z1gY61tbPE61nqDUVsyI1sqvXc5X0JAzRiEzGjF9fNvMX9pY9f+patziaK/ZYQ3brJEZ5hByw5pEFhDYzVRhj8YSHEH1XF+yV3ogs2stmS7ssDGdhzq8uv1yIrx5PyVZE7uouTYa32DUgRBXvDsnJbhd+If+GNmSnf64hnp7uMVLHofNsGvQDzh9K5REfRlfJhYU=
  - secure: C60fzcaEeHVTAD7xt9FF4zLg+vDNu0D+qVYOZSWnm6cTt5jvb1hIVlxoxjITHeZ+qhVFflZgmBio9ADTBSkE+7c0NryKUJfpErS8GJ4pf92tVE+0h37AmsghTKMEPCaxbs7+eIqsG5DxpOxKpnxLYsM4i+4AGbyRfOV9ig0D31PCp2XORiihzqh/u6XIt04dLDcdPLUfOwr68MuDVG2A8zGch6MNWyA84k9pa3H3dKIbhxKRGj8Ft3ARUUy4b9ifC4eFPJWzrrutik2I+wGUFuHltYba0ZpWZTikPWe3NHsgQ2+M2rN0k5UToDJ393uWhQPNc7x577JmJ8CXZz9nV6itsMmzp6Bfhzz8p8y3mRriQNAdjin1j070Q7dmSWsIG79dTq+6PufmDrnHkJlmgGA+oyEisqPATJSgT3q3XNitxLCFe3IobYkifdI3uSZKbZO6oR8rFhyIf0A5mQAAeKbErYzlMFYyOanwGXKAD37hbGdfMm4sPGTGHhOC1HztDS7vbYdotXIL4J6sX2lp3REhJATj0m6mFfzgDQtzGT58XWw9od/Q3qBmZyUZQjbuGgIQp5z9zbpGEdcs7MLLauX5RhbCkq/5IcxxmuGN7iJs69f0w1BPv3ASx7v9WzjPO4dybmxz+uFp/2KAxkQeWl1sbMdGEilG+qBs8G5Lp0o=
